antmodel:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1_lf
    pid: {p: 100.0, i: 0.01, d: 0.1}
  joint2_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2_lf
    pid: {p: 100.0, i: 0.01, d: 0.1}
  joint3_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3_lf
    pid: {p: 100.0, i: 0.01, d: 0.1}
  joint4_lf_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4_lf
    pid: {p: 100.0, i: 0.01, d: 0.1}
